# Generated by Django 5.0.4 on 2024-05-18 04:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_CBR_Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCBR', models.DateField()),
                ('RateUSD', models.CharField(max_length=200)),
                ('RateEUR', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['RateEUR'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientID', models.IntegerField()),
                ('ClientShortNameRU', models.CharField(max_length=56)),
                ('ClientShortNameEN', models.CharField(max_length=56)),
                ('ClientINN', models.BigIntegerField()),
                ('ClientKPP', models.IntegerField()),
            ],
            options={
                'ordering': ['ClientID'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractTypeEN', models.CharField(max_length=200)),
                ('ContractTypeRU', models.CharField(max_length=200)),
                ('ContractTypeTR', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['ContractTypeEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_CounterParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CounterPartyID_1C', models.CharField(blank=True, max_length=100)),
                ('CounterPartyEN', models.CharField(max_length=200)),
                ('CounterPartyRU', models.CharField(max_length=200)),
                ('CounterPartyTR', models.CharField(max_length=200)),
                ('CounterPartyINN', models.CharField(max_length=200)),
                ('CounterPartyKPP', models.CharField(blank=True, max_length=200)),
                ('Client', models.BooleanField(blank=True, default=False)),
                ('ClientGroup', models.CharField(blank=True, max_length=100)),
                ('Supplier', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ['CounterPartyEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_CounterPartyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CounterPartyTypeEN', models.CharField(max_length=200)),
                ('CounterPartyTypeRU', models.CharField(max_length=200)),
                ('CounterPartyTypeTR', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['CounterPartyTypeEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryCode', models.CharField(max_length=50, unique=True)),
                ('CountryEN', models.CharField(blank=True, max_length=100)),
                ('CountryRU', models.CharField(blank=True, max_length=100)),
                ('CountryTR', models.CharField(blank=True, max_length=100)),
                ('AlphaCode2', models.CharField(blank=True, max_length=10, verbose_name='AlphaCode(2)')),
                ('AlphaCode3', models.CharField(blank=True, max_length=10, verbose_name='AlphaCode(3)')),
                ('CountriesForRF', models.BooleanField(blank=True, default=False)),
                ('LocalEEC', models.BooleanField(blank=True, default=False, verbose_name='Local/ EEC')),
                ('RvpVnj', models.BooleanField(blank=True, default=False, verbose_name='RVP/ VNJ')),
                ('Visa', models.BooleanField(blank=True, default=False)),
                ('VKS', models.BooleanField(blank=True, default=False)),
                ('Patent', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ['CountryEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrencyNumber', models.IntegerField(unique=True)),
                ('CurrencyID_1C', models.CharField(blank=True, max_length=100)),
                ('CurrencyCode', models.CharField(blank=True, max_length=100)),
                ('CountryAlphaCode2', models.CharField(blank=True, max_length=10, verbose_name='AlphaCode(2)')),
                ('CountryAlphaCode3', models.CharField(blank=True, max_length=10, verbose_name='AlphaCode(3)')),
                ('CurrencyEN', models.CharField(blank=True, max_length=200)),
                ('CurrencyRU', models.CharField(blank=True, max_length=200)),
                ('CurrencyTR', models.CharField(blank=True, max_length=200)),
                ('ActiveCurr', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ['CurrencyNumber'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DisciplineEN', models.CharField(max_length=200)),
                ('DisciplineRU', models.CharField(max_length=200)),
                ('DisciplineTR', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['DisciplineEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentTypeEN', models.CharField(max_length=200)),
                ('DocumentTypeRU', models.CharField(max_length=200)),
                ('DocumentTypeTR', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['DocumentTypeEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_EmpClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpClassEN', models.CharField(max_length=200)),
                ('EmpClassRU', models.CharField(max_length=200)),
                ('EmpClassTR', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['EmpClassEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_EmpLegalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpLegalStatusEN', models.CharField(max_length=200)),
                ('EmpLegalStatusRU', models.CharField(max_length=200)),
                ('EmpLegalStatusTR', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['EmpLegalStatusEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_EmpLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpLevelEN', models.CharField(max_length=200)),
                ('EmpLevelRU', models.CharField(max_length=200)),
                ('EmpLevelTR', models.CharField(max_length=200)),
                ('OfficeEmp', models.BooleanField(blank=True, default=False)),
                ('ProjectEmp', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'ordering': ['EmpLevelEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_EmpTaxType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpTaxTypeEN', models.CharField(max_length=200)),
                ('EmpTaxTypeRU', models.CharField(max_length=200)),
                ('EmpTaxTypeTR', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['EmpTaxTypeEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_ExpenseFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpenseFrequencyEN', models.CharField(max_length=200)),
                ('ExpenseFrequencyRU', models.CharField(max_length=200)),
                ('ExpenseFrequencyTR', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['ExpenseFrequencyEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectID_1C', models.CharField(blank=True, max_length=100)),
                ('ProjectCode', models.CharField(blank=True, max_length=200)),
                ('ProjectNameEN', models.CharField(max_length=200)),
                ('ProjectNameRU', models.CharField(max_length=200)),
                ('ProjectNameTR', models.CharField(max_length=200)),
                ('AddressEN', models.CharField(blank=True, max_length=200)),
                ('AddressRU', models.CharField(blank=True, max_length=200)),
                ('AddressTR', models.CharField(blank=True, max_length=200)),
                ('StartDate', models.DateField(blank=True)),
                ('EndDate', models.DateField(blank=True)),
            ],
            options={
                'ordering': ['ProjectNameEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_SubjectOfRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectOfRF_EN', models.CharField(max_length=200)),
                ('SubjectOfRF_RU', models.CharField(max_length=200)),
                ('SubjectOfRF_TR', models.CharField(max_length=200)),
                ('SubjRF_Abbreviation', models.CharField(blank=True, max_length=200)),
                ('FederalDistrictEN', models.CharField(blank=True, max_length=200)),
                ('FederalDistrictRU', models.CharField(blank=True, max_length=200)),
                ('FederalDistrictTR', models.CharField(blank=True, max_length=200)),
                ('OKATO_CODE', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['SubjectOfRF_EN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_UoM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UoM_Code_1C', models.CharField(blank=True, max_length=20)),
                ('UoM_Short_EN', models.CharField(max_length=200)),
                ('UoM_Short_RU', models.CharField(max_length=200)),
                ('UoM_Short_TR', models.CharField(max_length=200)),
                ('UoM_EN', models.CharField(blank=True, max_length=200)),
                ('UoM_RU', models.CharField(blank=True, max_length=200)),
                ('UoM_TR', models.CharField(blank=True, max_length=200)),
                ('UoM_Active', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'ordering': ['UoM_Short_EN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_VAT_Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VAT_Rate', models.IntegerField()),
            ],
            options={
                'ordering': ['VAT_Rate'],
            },
        ),
        migrations.CreateModel(
            name='PermitDocCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gen_DT_BudgetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VersionDate', models.DateField(default=django.utils.timezone.now)),
                ('BudgetVersion', models.IntegerField(default=1)),
                ('Status', models.CharField(choices=[('success', 'success'), ('rejected', 'rejected')], max_length=56)),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_EmpTaxCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpTaxRateEN', models.CharField(max_length=200)),
                ('EmpTaxRateRU', models.CharField(max_length=200)),
                ('EmpTaxRateTR', models.CharField(max_length=200)),
                ('TaxCodeSSF', models.IntegerField(blank=True)),
                ('TaxCodePIT_Until182day', models.IntegerField(blank=True)),
                ('TaxCodePIT_After182day', models.IntegerField(blank=True)),
                ('LegDocumentType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_documenttype', verbose_name='Document Type')),
            ],
            options={
                'ordering': ['EmpTaxRateEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_EmpTaxPayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpTaxCategoryCode', models.CharField(blank=True, max_length=200)),
                ('EmpTaxCategoryEN', models.CharField(max_length=200)),
                ('EmpTaxCategoryRU', models.CharField(max_length=200)),
                ('EmpTaxCategoryTR', models.CharField(max_length=200)),
                ('UniformBaseValueLimitUCVB', models.FloatField(verbose_name='UniformBaseValueLimit(UCVB)')),
                ('WithinLimit', models.FloatField(blank=True)),
                ('AboveLimit', models.FloatField(blank=True)),
                ('EmpTaxType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_emptaxtype', verbose_name='Employee Tax Type')),
            ],
            options={
                'ordering': ['EmpTaxCategoryEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpenseTypeEN', models.CharField(max_length=200)),
                ('ExpenseTypeRU', models.CharField(max_length=200)),
                ('ExpenseTypeTR', models.CharField(max_length=200)),
                ('ExpenseFrequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_expensefrequency', verbose_name='Expense Frequency')),
            ],
            options={
                'ordering': ['ExpenseTypeEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitleEN', models.CharField(max_length=200)),
                ('JobTitleRU', models.CharField(max_length=200)),
                ('JobTitleTR', models.CharField(max_length=200)),
                ('EmpClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_empclass', verbose_name='Employee Class')),
                ('EmpLevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_emplevel', verbose_name='Employee Level')),
            ],
            options={
                'ordering': ['JobTitleEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_OurCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OurCompanyID_1C', models.CharField(blank=True, max_length=100)),
                ('OurCompanyEN', models.CharField(max_length=200)),
                ('OurCompanyRU', models.CharField(max_length=200)),
                ('OurCompanyTR', models.CharField(max_length=200)),
                ('OurCompanyINN', models.CharField(blank=True, max_length=200)),
                ('OurCompanyKPP', models.CharField(blank=True, max_length=200)),
                ('ShortCode', models.CharField(blank=True, max_length=100)),
                ('TaxPayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_emptaxpayer', verbose_name='Tax Payer')),
            ],
            options={
                'ordering': ['OurCompanyEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractID_1C', models.CharField(blank=True, max_length=100)),
                ('ContractsNo', models.CharField(max_length=200)),
                ('ContractDate', models.DateField(blank=True)),
                ('ContractsSubject', models.CharField(blank=True, max_length=200)),
                ('ContractAmountVatWo', models.FloatField(blank=True)),
                ('ContractStartDate', models.DateField(blank=True)),
                ('ContractEndDate', models.DateField(blank=True)),
                ('ContractType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_contracttype', verbose_name='Contract Type')),
                ('CounterParty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_counterparty', verbose_name='Counter Party')),
                ('CounterPartyType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_counterpartytype', verbose_name='Counter Party Type')),
                ('Currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_currency', verbose_name='Currency')),
                ('OurCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_ourcompany', verbose_name='Our Company')),
                ('Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_project', verbose_name='Project')),
                ('VAT_Rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_vat_rate', verbose_name='VAT Rate')),
            ],
            options={
                'ordering': ['ContractsSubject'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_PaymentBDHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FloatingRate', models.IntegerField(blank=True)),
                ('FixedRate', models.IntegerField(blank=True)),
                ('FixedRateCurrency', models.FloatField(blank=True)),
                ('PaymentBreakdownDate', models.DateField(blank=True)),
                ('ContractID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_contract', verbose_name='Contract')),
            ],
            options={
                'ordering': ['PaymentBreakdownDate'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_ProgressDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentID_1C', models.CharField(blank=True, max_length=200)),
                ('ProgressPeriodStart', models.DateField(blank=True)),
                ('ProgressPeriodEnd', models.DateField(blank=True)),
                ('ProgressDate', models.DateField(blank=True)),
                ('ProgressAmountVatWo', models.IntegerField(blank=True)),
                ('AdvanceDeduction', models.IntegerField(blank=True)),
                ('OtherDeductions', models.IntegerField(blank=True)),
                ('current_status', models.CharField(choices=[('signed', 'Подписано'), ('approved', 'Одобрено')], default='signed', max_length=15, verbose_name='Статус')),
                ('PBHistoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_paymentbdhistory', verbose_name='Payment BreakDown History')),
            ],
            options={
                'ordering': ['PaymentID_1C'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentID_1C', models.CharField(blank=True, max_length=200)),
                ('PaymentDate', models.DateField(blank=True)),
                ('PaymentType', models.CharField(choices=[('Advance', 'Аванс'), ('Progress', 'Прогресс'), ('3rd Party', '3ая сторона')], default='Advance', max_length=10, verbose_name='Тип оплаты')),
                ('PaymentBreakdown', models.FloatField(blank=True)),
                ('PaymentAmountFloating', models.FloatField(blank=True)),
                ('PaymentAmountFixed', models.FloatField(blank=True)),
                ('PaymentCurrencyFixed', models.FloatField(blank=True)),
                ('Comment', models.CharField(blank=True, max_length=200)),
                ('ContractID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_contract', verbose_name='Contract')),
                ('PaymentCurrencyFloating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_currency', verbose_name='Progress Docs')),
                ('ProgressID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_progressdocs', verbose_name='Progress Docs')),
            ],
            options={
                'ordering': ['PaymentID_1C'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_LegalExpences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpensePrice', models.FloatField(blank=True)),
                ('LegalExpenseActive', models.BooleanField(blank=True, default=True)),
                ('EffectiveDate', models.DateField(blank=True)),
                ('Currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_currency', verbose_name='Currency')),
                ('ExpeneseCountry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_country', verbose_name='Expenese Country')),
                ('ExpenseType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_expensetype', verbose_name='Expense Type')),
                ('LegDocumentType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_documenttype', verbose_name='Document Type')),
                ('ProjectID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_project', verbose_name='Project ID')),
            ],
            options={
                'ordering': ['ProjectID'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_BudgetDataHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BudgetDate', models.DateField()),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('BudgetID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_budgetdata', verbose_name='Budget ID')),
                ('ProjectID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_project', verbose_name='Project ID')),
            ],
            options={
                'ordering': ['BudgetDate'],
            },
        ),
        migrations.AddField(
            model_name='gen_dt_project',
            name='SubjectofRF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_subjectofrf', verbose_name='Subject of RF'),
        ),
        migrations.CreateModel(
            name='Gen_DT_PatentPricesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegionalCoefficient_Base', models.CharField(max_length=256)),
                ('Amount', models.FloatField(blank=True)),
                ('MonthlyPatentPayment', models.FloatField(null=True)),
                ('Active', models.BooleanField()),
                ('Effective_Date', models.DateField(blank=True)),
                ('SubjectofRF_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_subjectofrf', verbose_name='Gen_DT_SubjectOfRF')),
            ],
            options={
                'ordering': ['SubjectofRF_ID'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_BudgetDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BudgetCode', models.CharField(blank=True, max_length=100)),
                ('PrimaveraCode', models.CharField(blank=True, max_length=100)),
                ('StartOfWorkDate', models.DateField(blank=True)),
                ('EndOfWorkDate', models.DateField(blank=True)),
                ('EmpQty', models.IntegerField(blank=True)),
                ('EmpNetSalary', models.FloatField(blank=True)),
                ('Budget_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_budgetdata', verbose_name='Budget ID')),
                ('Currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_currency', verbose_name='Currency')),
                ('Discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_discipline', verbose_name='Discipline')),
                ('LegDocumentType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_documenttype', verbose_name='Document Type')),
                ('JotTitle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_jobtitle', verbose_name='Job Title')),
                ('UoM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_uom', verbose_name='UoM')),
            ],
            options={
                'ordering': ['BudgetCode'],
            },
        ),
    ]
