# Generated by Django 5.0.4 on 2024-05-21 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gen_dt_budgetdata',
            name='Project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='corecode.gen_dt_project'),
            preserve_default=False,
        ),
    ]
