# Generated by Django 5.0.4 on 2024-04-12 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientID', models.IntegerField()),
                ('ClientShortNameRU', models.CharField(max_length=56)),
                ('ClientShortNameEN', models.CharField(max_length=56)),
                ('ClientINN', models.BigIntegerField()),
                ('ClientKPP', models.IntegerField()),
            ],
            options={
                'ordering': ['ClientID'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_PatentPricesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegionalCoefficient_Base', models.CharField(max_length=256)),
                ('Amount', models.FloatField(blank=True)),
                ('MonthlyPatentPayment', models.FloatField(null=True)),
                ('Active', models.BooleanField()),
                ('Effective_Date', models.DateField(blank=True)),
                ('SubjectofRF_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_subjectofrf', verbose_name='Gen_DT_SubjectOfRF')),
            ],
            options={
                'ordering': ['SubjectofRF_ID'],
            },
        ),
    ]
