# Generated by Django 5.0.4 on 2024-05-24 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_remove_gen_dt_expensetype_expensefrequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='gen_dt_legalexpences',
            name='ExpenseFrequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_expensefrequency', verbose_name='Expense Frequency'),
        ),
    ]
