# Generated by Django 5.0.4 on 2024-05-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0005_gen_dt_legalexpences_expensefrequency'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gen_dt_budgetdetails',
            index=models.Index(fields=['Budget_ID'], name='corecode_ge_Budget__5893d6_idx'),
        ),
    ]
