# Generated by Django 4.1.5 on 2024-02-29 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0036_alter_gen_dt_contract_ourcompany_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gen_dt_budgetdata',
            name='BudgetCode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gen_dt_budgetdata',
            name='EmpNetSalary',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_budgetdata',
            name='EmpQty',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_budgetdata',
            name='EndOfWorkDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_budgetdata',
            name='PrimaveraCode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gen_dt_budgetdata',
            name='StartOfWorkDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_contract',
            name='ContractAmountVatWo',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_contract',
            name='ContractDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_contract',
            name='ContractEndDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_contract',
            name='ContractID_1C',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gen_dt_contract',
            name='ContractStartDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_contract',
            name='ContractsSubject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_counterparty',
            name='Client',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='gen_dt_counterparty',
            name='ClientGroup',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gen_dt_counterparty',
            name='CounterPartyID_1C',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gen_dt_counterparty',
            name='CounterPartyKPP',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_counterparty',
            name='Supplier',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='gen_dt_country',
            name='AlphaCode2',
            field=models.CharField(blank=True, max_length=10, verbose_name='AlphaCode(2)'),
        ),
        migrations.AlterField(
            model_name='gen_dt_country',
            name='AlphaCode3',
            field=models.CharField(blank=True, max_length=10, verbose_name='AlphaCode(3)'),
        ),
        migrations.AlterField(
            model_name='gen_dt_country',
            name='CountriesForRF',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='gen_dt_country',
            name='CountryEN',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gen_dt_country',
            name='CountryRU',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gen_dt_country',
            name='CountryTR',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gen_dt_country',
            name='LocalEEC',
            field=models.BooleanField(blank=True, default=False, verbose_name='Local/ EEC'),
        ),
        migrations.AlterField(
            model_name='gen_dt_country',
            name='Patent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='gen_dt_country',
            name='RvpVnj',
            field=models.BooleanField(blank=True, default=False, verbose_name='RVP/ VNJ'),
        ),
        migrations.AlterField(
            model_name='gen_dt_country',
            name='VKS',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='gen_dt_country',
            name='Visa',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='gen_dt_currency',
            name='ActiveCurr',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='gen_dt_currency',
            name='CountryAlphaCode2',
            field=models.CharField(blank=True, max_length=10, verbose_name='AlphaCode(2)'),
        ),
        migrations.AlterField(
            model_name='gen_dt_currency',
            name='CountryAlphaCode3',
            field=models.CharField(blank=True, max_length=10, verbose_name='AlphaCode(3)'),
        ),
        migrations.AlterField(
            model_name='gen_dt_currency',
            name='CurrencyCode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gen_dt_currency',
            name='CurrencyEN',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_currency',
            name='CurrencyID_1C',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gen_dt_currency',
            name='CurrencyRU',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_currency',
            name='CurrencyTR',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_emplevel',
            name='OfficeEmp',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='gen_dt_emplevel',
            name='ProjectEmp',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_emptaxcalc',
            name='TaxCodePIT_After182day',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_emptaxcalc',
            name='TaxCodePIT_Until182day',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_emptaxcalc',
            name='TaxCodeSSF',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_emptaxpayer',
            name='AboveLimit',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_emptaxpayer',
            name='EmpTaxCategoryCode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_emptaxpayer',
            name='WithinLimit',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_legalexpences',
            name='EffectiveDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_legalexpences',
            name='ExpensePrice',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_legalexpences',
            name='LegalExpenseActive',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_ourcompany',
            name='OurCompanyID_1C',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gen_dt_ourcompany',
            name='OurCompanyINN',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_ourcompany',
            name='OurCompanyKPP',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_ourcompany',
            name='ShortCode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gen_dt_project',
            name='AddressEN',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_project',
            name='AddressRU',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_project',
            name='AddressTR',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_project',
            name='EndDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_project',
            name='ProjectCode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_project',
            name='ProjectID_1C',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gen_dt_project',
            name='StartDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_subjectofrf',
            name='FederalDistrictEN',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_subjectofrf',
            name='FederalDistrictRU',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_subjectofrf',
            name='FederalDistrictTR',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_subjectofrf',
            name='OKATO_CODE',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_subjectofrf',
            name='SubjRF_Abbreviation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_uom',
            name='UoM_Active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='gen_dt_uom',
            name='UoM_Code_1C',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='gen_dt_uom',
            name='UoM_EN',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_uom',
            name='UoM_RU',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gen_dt_uom',
            name='UoM_TR',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Gen_DT_PaymentBDHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FloatingRate', models.IntegerField(blank=True)),
                ('FixedRate', models.IntegerField(blank=True)),
                ('FixedRateCurrency', models.FloatField(blank=True)),
                ('PaymentBreakdownDate', models.DateField(blank=True)),
                ('ContractID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_contract', verbose_name='Contract')),
            ],
            options={
                'ordering': ['PaymentBreakdownDate'],
            },
        ),
    ]
